### ISSUE TITLE
Minecraft crashes after going into video settings

### ISSUE THREAD

**Issue by LapizPlayz** [FlashyReese/reeses-sodium-options#124]
I'm not gonna make you scroll through hundreds of lines of code to get to the messages, so... [here's](https://mclo.gs/9pkSS1h) the thing on mclo.gs. Mod is Reese's Sodium Options (obviously) and on version... [mc1.21.1-1.8.0-beta.4+fabric](https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.4+fabric).

**Comment by EnchantedHay** [comment]
same problem here

**Comment by FlashyReese** [comment]
More than likely caused by Controlify, they are mixing our code for controller support

**Comment by murolem** [comment]
> More than likely caused by Controlify, they are mixing our code for controller support

Can confirm. After disabling Controlify, video settings are able to open.

**Comment by LapizPlayz** [comment]
> > More than likely caused by Controlify, they are mixing our code for controller support
> 
> Can confirm. After disabling Controlify, video settings are able to open.

guess I have to use another controller support mod :\

**Comment by NotApel** [comment]
> Owner
Thank you so much my head hurts trying to figure out the problems

**Comment by kxtzownsu** [comment]
Same issue here, tested disabling Controlify & video settings opens. 
I'd like to note that I'm on Sodium 0.6.5 for 1.21.1, Iris 1.8.1 for 1.21.1, and Sodium Extra 0.6.0 for 1.21.1.

Heres the error log from when Controlify was enabled: 
```
[16:24:09] [Render thread/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/SodiumOptionsGUI (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumOptionsGUI)
[16:24:09] [Render thread/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/widgets/FlatButtonWidget (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/widgets/FlatButtonWidget)
[16:24:09] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at knot/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_429.handler$eaf000$sodium$open(class_429.java:1525) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_429.handler$eaf000$sodium$open(class_429.java:1525) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: me.jellysquid.mods.sodium.client.gui.widgets.FlatButtonWidget
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1016) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:920) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:608) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_429.handler$eaf000$sodium$open(class_429.java:1525) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_19828(class_429.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_429.method_47624(class_429.java:171) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 19 more
[16:24:09] [Render thread/INFO]: [ETF]: emissive suffixes loaded: {_e}.
[16:24:10] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
```
