### ISSUE TITLE
Crash with Sodium 0.4

### ISSUE THREAD

**Issue by andreasdc** [FlashyReese/reeses-sodium-options#22]
[17:34:32] [Render thread/ERROR]: Mixin apply for mod sodium-extra failed sodium-extra.mixins.json:reeses_sodium_options.MixinSodiumVideoOptionsScreen -> me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field applyButton was not located in the target class me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen. Using refmap sodium-extra-mc1.17.1-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field applyButton was not located in the target class me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen. Using refmap sodium-extra-mc1.17.1-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.32) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19840(GameMenuScreen:62) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[17:34:32] [Render thread/INFO]: Stopping worker threads
[17:34:32] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.32) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:495) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19840(GameMenuScreen:62) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19840(GameMenuScreen:62) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	... 27 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [sodium-extra.mixins.json:reeses_sodium_options.MixinSodiumVideoOptionsScreen] from phase [DEFAULT] in config [sodium-extra.mixins.json] from mod [sodium-extra] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19840(GameMenuScreen:62) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field applyButton was not located in the target class me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen. Using refmap sodium-extra-mc1.17.1-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.32) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.6+mixin.0.8.4.jar:0.10.6+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) ~[fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19840(GameMenuScreen:62) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	... 27 more

**Comment by DragonEggBedrockBreaking** [comment]
Please send a full log. Are you using the 0.4-experiments branch on 1.17.1, because that requires you to build a separate branch, which is not supported. Or are you using the released 0.4 alpha for 1.18, in which case make sure you update to the latest versions of the mods. Once again, a full log will help with this.

**Comment by andreasdc** [comment]
> Please send a full log. Are you using the 0.4-experiments branch on 1.17.1, because that requires you to build a separate branch, which is not supported. Or are you using the released 0.4 alpha for 1.18, in which case make sure you update to the latest versions of the mods. Once again, a full log will help with this.

I'm using 0.4 experiments for 1.17.1 from github.

**Comment by DragonEggBedrockBreaking** [comment]
The. You need to compile the relevant branch that is compatible with it.

**Comment by andreasdc** [comment]
> The. You need to compile the relevant branch that is compatible with it.

Which branch is compatible with 0.4?

**Comment by DragonEggBedrockBreaking** [comment]
> > The. You need to compile the relevant branch that is compatible with it.
> 
> Which branch is compatible with 0.4?

1.17.x/dev-sodium-0.4.0-experiments

**Comment by andreasdc** [comment]
> 

But you said its not compatible with 0.4

**Comment by DragonEggBedrockBreaking** [comment]
> But you said its not compatible with 0.4

No, I said normal reeses sodium options is not compatible. So you have compiled that branch and the branch on sodium? Then as I said, please send a full log.

**Comment by andreasdc** [comment]
> > But you said its not compatible with 0.4
> 
> No, I said normal reeses sodium options is not compatible. So you have compiled that branch and the branch on sodium? Then as I said, please send a full log.

How to get reeses sodium options compatible with 0.4?

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/reeses-sodium-options/suites/3812546719/artifacts/94243413

**Comment by andreasdc** [comment]
Ok, so the only feature is new menu right?

**Comment by FlashyReese** [comment]
Yup

**Comment by andreasdc** [comment]
> Yup

 - Mod 'Sodium Extra' (sodium-extra) recommends any version of reeses-sodium-options, which is missing!
	 - You should install any version of reeses-sodium-options for the optimal experience.
This message means something different xd

**Comment by FlashyReese** [comment]
Reese's Sodium Options only changes the menu, if you don't want Sodium Extra you can remove it, it's not mandatory to have it installed.

Also you posted this in Reese's Sodium Options issue tracker so I have no idea what you are getting at.
